// Code generated by go-swagger; DO NOT EDIT.

package ticket_projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewTicketProjectsDeleteProjectParams creates a new TicketProjectsDeleteProjectParams object
// with the default values initialized.
func NewTicketProjectsDeleteProjectParams() *TicketProjectsDeleteProjectParams {
	var ()
	return &TicketProjectsDeleteProjectParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewTicketProjectsDeleteProjectParamsWithTimeout creates a new TicketProjectsDeleteProjectParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewTicketProjectsDeleteProjectParamsWithTimeout(timeout time.Duration) *TicketProjectsDeleteProjectParams {
	var ()
	return &TicketProjectsDeleteProjectParams{

		timeout: timeout,
	}
}

// NewTicketProjectsDeleteProjectParamsWithContext creates a new TicketProjectsDeleteProjectParams object
// with the default values initialized, and the ability to set a context for a request
func NewTicketProjectsDeleteProjectParamsWithContext(ctx context.Context) *TicketProjectsDeleteProjectParams {
	var ()
	return &TicketProjectsDeleteProjectParams{

		Context: ctx,
	}
}

// NewTicketProjectsDeleteProjectParamsWithHTTPClient creates a new TicketProjectsDeleteProjectParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewTicketProjectsDeleteProjectParamsWithHTTPClient(client *http.Client) *TicketProjectsDeleteProjectParams {
	var ()
	return &TicketProjectsDeleteProjectParams{
		HTTPClient: client,
	}
}

/*TicketProjectsDeleteProjectParams contains all the parameters to send to the API endpoint
for the ticket projects delete project operation typically these are written to a http.Request
*/
type TicketProjectsDeleteProjectParams struct {

	/*ID
	  A unique integer value identifying this project.

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the ticket projects delete project params
func (o *TicketProjectsDeleteProjectParams) WithTimeout(timeout time.Duration) *TicketProjectsDeleteProjectParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the ticket projects delete project params
func (o *TicketProjectsDeleteProjectParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the ticket projects delete project params
func (o *TicketProjectsDeleteProjectParams) WithContext(ctx context.Context) *TicketProjectsDeleteProjectParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the ticket projects delete project params
func (o *TicketProjectsDeleteProjectParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the ticket projects delete project params
func (o *TicketProjectsDeleteProjectParams) WithHTTPClient(client *http.Client) *TicketProjectsDeleteProjectParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the ticket projects delete project params
func (o *TicketProjectsDeleteProjectParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the ticket projects delete project params
func (o *TicketProjectsDeleteProjectParams) WithID(id int64) *TicketProjectsDeleteProjectParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the ticket projects delete project params
func (o *TicketProjectsDeleteProjectParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *TicketProjectsDeleteProjectParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
