// Code generated by go-swagger; DO NOT EDIT.

package ticket_projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewTicketProjectsReadParams creates a new TicketProjectsReadParams object
// with the default values initialized.
func NewTicketProjectsReadParams() *TicketProjectsReadParams {
	var ()
	return &TicketProjectsReadParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewTicketProjectsReadParamsWithTimeout creates a new TicketProjectsReadParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewTicketProjectsReadParamsWithTimeout(timeout time.Duration) *TicketProjectsReadParams {
	var ()
	return &TicketProjectsReadParams{

		timeout: timeout,
	}
}

// NewTicketProjectsReadParamsWithContext creates a new TicketProjectsReadParams object
// with the default values initialized, and the ability to set a context for a request
func NewTicketProjectsReadParamsWithContext(ctx context.Context) *TicketProjectsReadParams {
	var ()
	return &TicketProjectsReadParams{

		Context: ctx,
	}
}

// NewTicketProjectsReadParamsWithHTTPClient creates a new TicketProjectsReadParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewTicketProjectsReadParamsWithHTTPClient(client *http.Client) *TicketProjectsReadParams {
	var ()
	return &TicketProjectsReadParams{
		HTTPClient: client,
	}
}

/*TicketProjectsReadParams contains all the parameters to send to the API endpoint
for the ticket projects read operation typically these are written to a http.Request
*/
type TicketProjectsReadParams struct {

	/*ID
	  A unique integer value identifying this project.

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the ticket projects read params
func (o *TicketProjectsReadParams) WithTimeout(timeout time.Duration) *TicketProjectsReadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the ticket projects read params
func (o *TicketProjectsReadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the ticket projects read params
func (o *TicketProjectsReadParams) WithContext(ctx context.Context) *TicketProjectsReadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the ticket projects read params
func (o *TicketProjectsReadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the ticket projects read params
func (o *TicketProjectsReadParams) WithHTTPClient(client *http.Client) *TicketProjectsReadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the ticket projects read params
func (o *TicketProjectsReadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the ticket projects read params
func (o *TicketProjectsReadParams) WithID(id int64) *TicketProjectsReadParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the ticket projects read params
func (o *TicketProjectsReadParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *TicketProjectsReadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
