// Code generated by go-swagger; DO NOT EDIT.

package group_settings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGroupSettingsListParams creates a new GroupSettingsListParams object
// with the default values initialized.
func NewGroupSettingsListParams() *GroupSettingsListParams {
	var ()
	return &GroupSettingsListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGroupSettingsListParamsWithTimeout creates a new GroupSettingsListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGroupSettingsListParamsWithTimeout(timeout time.Duration) *GroupSettingsListParams {
	var ()
	return &GroupSettingsListParams{

		timeout: timeout,
	}
}

// NewGroupSettingsListParamsWithContext creates a new GroupSettingsListParams object
// with the default values initialized, and the ability to set a context for a request
func NewGroupSettingsListParamsWithContext(ctx context.Context) *GroupSettingsListParams {
	var ()
	return &GroupSettingsListParams{

		Context: ctx,
	}
}

// NewGroupSettingsListParamsWithHTTPClient creates a new GroupSettingsListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGroupSettingsListParamsWithHTTPClient(client *http.Client) *GroupSettingsListParams {
	var ()
	return &GroupSettingsListParams{
		HTTPClient: client,
	}
}

/*GroupSettingsListParams contains all the parameters to send to the API endpoint
for the group settings list operation typically these are written to a http.Request
*/
type GroupSettingsListParams struct {

	/*Filters
	  Complex filter that handles filtering with groups of conditions connected with AND and OR conjunctions. The query can be arbitrarily grouped and nested.

	*/
	Filters *string
	/*ID*/
	ID *float64
	/*IDIn
	  Multiple values may be separated by commas.

	*/
	IDIn *float64
	/*Limit
	  Number of results to return per page.

	*/
	Limit *int64
	/*Offset
	  The initial index from which to return the results.

	*/
	Offset *int64
	/*Ordering
	  Valid ordering fields are: `id`

	*/
	Ordering *string
	/*Org
	  Filter-traversable object

	*/
	Org *string
	/*Search
	  A search term.

	*/
	Search *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the group settings list params
func (o *GroupSettingsListParams) WithTimeout(timeout time.Duration) *GroupSettingsListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the group settings list params
func (o *GroupSettingsListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the group settings list params
func (o *GroupSettingsListParams) WithContext(ctx context.Context) *GroupSettingsListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the group settings list params
func (o *GroupSettingsListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the group settings list params
func (o *GroupSettingsListParams) WithHTTPClient(client *http.Client) *GroupSettingsListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the group settings list params
func (o *GroupSettingsListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFilters adds the filters to the group settings list params
func (o *GroupSettingsListParams) WithFilters(filters *string) *GroupSettingsListParams {
	o.SetFilters(filters)
	return o
}

// SetFilters adds the filters to the group settings list params
func (o *GroupSettingsListParams) SetFilters(filters *string) {
	o.Filters = filters
}

// WithID adds the id to the group settings list params
func (o *GroupSettingsListParams) WithID(id *float64) *GroupSettingsListParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the group settings list params
func (o *GroupSettingsListParams) SetID(id *float64) {
	o.ID = id
}

// WithIDIn adds the iDIn to the group settings list params
func (o *GroupSettingsListParams) WithIDIn(iDIn *float64) *GroupSettingsListParams {
	o.SetIDIn(iDIn)
	return o
}

// SetIDIn adds the idIn to the group settings list params
func (o *GroupSettingsListParams) SetIDIn(iDIn *float64) {
	o.IDIn = iDIn
}

// WithLimit adds the limit to the group settings list params
func (o *GroupSettingsListParams) WithLimit(limit *int64) *GroupSettingsListParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the group settings list params
func (o *GroupSettingsListParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithOffset adds the offset to the group settings list params
func (o *GroupSettingsListParams) WithOffset(offset *int64) *GroupSettingsListParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the group settings list params
func (o *GroupSettingsListParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WithOrdering adds the ordering to the group settings list params
func (o *GroupSettingsListParams) WithOrdering(ordering *string) *GroupSettingsListParams {
	o.SetOrdering(ordering)
	return o
}

// SetOrdering adds the ordering to the group settings list params
func (o *GroupSettingsListParams) SetOrdering(ordering *string) {
	o.Ordering = ordering
}

// WithOrg adds the org to the group settings list params
func (o *GroupSettingsListParams) WithOrg(org *string) *GroupSettingsListParams {
	o.SetOrg(org)
	return o
}

// SetOrg adds the org to the group settings list params
func (o *GroupSettingsListParams) SetOrg(org *string) {
	o.Org = org
}

// WithSearch adds the search to the group settings list params
func (o *GroupSettingsListParams) WithSearch(search *string) *GroupSettingsListParams {
	o.SetSearch(search)
	return o
}

// SetSearch adds the search to the group settings list params
func (o *GroupSettingsListParams) SetSearch(search *string) {
	o.Search = search
}

// WriteToRequest writes these params to a swagger request
func (o *GroupSettingsListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Filters != nil {

		// query param filters
		var qrFilters string
		if o.Filters != nil {
			qrFilters = *o.Filters
		}
		qFilters := qrFilters
		if qFilters != "" {
			if err := r.SetQueryParam("filters", qFilters); err != nil {
				return err
			}
		}

	}

	if o.ID != nil {

		// query param id
		var qrID float64
		if o.ID != nil {
			qrID = *o.ID
		}
		qID := swag.FormatFloat64(qrID)
		if qID != "" {
			if err := r.SetQueryParam("id", qID); err != nil {
				return err
			}
		}

	}

	if o.IDIn != nil {

		// query param id__in
		var qrIDIn float64
		if o.IDIn != nil {
			qrIDIn = *o.IDIn
		}
		qIDIn := swag.FormatFloat64(qrIDIn)
		if qIDIn != "" {
			if err := r.SetQueryParam("id__in", qIDIn); err != nil {
				return err
			}
		}

	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	if o.Ordering != nil {

		// query param ordering
		var qrOrdering string
		if o.Ordering != nil {
			qrOrdering = *o.Ordering
		}
		qOrdering := qrOrdering
		if qOrdering != "" {
			if err := r.SetQueryParam("ordering", qOrdering); err != nil {
				return err
			}
		}

	}

	if o.Org != nil {

		// query param org
		var qrOrg string
		if o.Org != nil {
			qrOrg = *o.Org
		}
		qOrg := qrOrg
		if qOrg != "" {
			if err := r.SetQueryParam("org", qOrg); err != nil {
				return err
			}
		}

	}

	if o.Search != nil {

		// query param search
		var qrSearch string
		if o.Search != nil {
			qrSearch = *o.Search
		}
		qSearch := qrSearch
		if qSearch != "" {
			if err := r.SetQueryParam("search", qSearch); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
