// Code generated by go-swagger; DO NOT EDIT.

package roles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewRolesReadParams creates a new RolesReadParams object
// with the default values initialized.
func NewRolesReadParams() *RolesReadParams {
	var ()
	return &RolesReadParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRolesReadParamsWithTimeout creates a new RolesReadParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRolesReadParamsWithTimeout(timeout time.Duration) *RolesReadParams {
	var ()
	return &RolesReadParams{

		timeout: timeout,
	}
}

// NewRolesReadParamsWithContext creates a new RolesReadParams object
// with the default values initialized, and the ability to set a context for a request
func NewRolesReadParamsWithContext(ctx context.Context) *RolesReadParams {
	var ()
	return &RolesReadParams{

		Context: ctx,
	}
}

// NewRolesReadParamsWithHTTPClient creates a new RolesReadParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRolesReadParamsWithHTTPClient(client *http.Client) *RolesReadParams {
	var ()
	return &RolesReadParams{
		HTTPClient: client,
	}
}

/*RolesReadParams contains all the parameters to send to the API endpoint
for the roles read operation typically these are written to a http.Request
*/
type RolesReadParams struct {

	/*ID
	  A unique integer value identifying this role.

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the roles read params
func (o *RolesReadParams) WithTimeout(timeout time.Duration) *RolesReadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the roles read params
func (o *RolesReadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the roles read params
func (o *RolesReadParams) WithContext(ctx context.Context) *RolesReadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the roles read params
func (o *RolesReadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the roles read params
func (o *RolesReadParams) WithHTTPClient(client *http.Client) *RolesReadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the roles read params
func (o *RolesReadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the roles read params
func (o *RolesReadParams) WithID(id int64) *RolesReadParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the roles read params
func (o *RolesReadParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *RolesReadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
