// Code generated by go-swagger; DO NOT EDIT.

package available_ticket_projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// AvailableTicketProjectsListReader is a Reader for the AvailableTicketProjectsList structure.
type AvailableTicketProjectsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AvailableTicketProjectsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAvailableTicketProjectsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewAvailableTicketProjectsListOK creates a AvailableTicketProjectsListOK with default headers values
func NewAvailableTicketProjectsListOK() *AvailableTicketProjectsListOK {
	return &AvailableTicketProjectsListOK{}
}

/*AvailableTicketProjectsListOK handles this case with default header values.

AvailableTicketProjectsListOK available ticket projects list o k
*/
type AvailableTicketProjectsListOK struct {
	Payload interface{}
}

func (o *AvailableTicketProjectsListOK) Error() string {
	return fmt.Sprintf("[GET /v3/customer/core/available_ticket_projects/][%d] availableTicketProjectsListOK  %+v", 200, o.Payload)
}

func (o *AvailableTicketProjectsListOK) GetPayload() interface{} {
	return o.Payload
}

func (o *AvailableTicketProjectsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
