// Code generated by go-swagger; DO NOT EDIT.

package pull_request_comments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewPullRequestCommentsReadParams creates a new PullRequestCommentsReadParams object
// with the default values initialized.
func NewPullRequestCommentsReadParams() *PullRequestCommentsReadParams {
	var ()
	return &PullRequestCommentsReadParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPullRequestCommentsReadParamsWithTimeout creates a new PullRequestCommentsReadParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPullRequestCommentsReadParamsWithTimeout(timeout time.Duration) *PullRequestCommentsReadParams {
	var ()
	return &PullRequestCommentsReadParams{

		timeout: timeout,
	}
}

// NewPullRequestCommentsReadParamsWithContext creates a new PullRequestCommentsReadParams object
// with the default values initialized, and the ability to set a context for a request
func NewPullRequestCommentsReadParamsWithContext(ctx context.Context) *PullRequestCommentsReadParams {
	var ()
	return &PullRequestCommentsReadParams{

		Context: ctx,
	}
}

// NewPullRequestCommentsReadParamsWithHTTPClient creates a new PullRequestCommentsReadParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPullRequestCommentsReadParamsWithHTTPClient(client *http.Client) *PullRequestCommentsReadParams {
	var ()
	return &PullRequestCommentsReadParams{
		HTTPClient: client,
	}
}

/*PullRequestCommentsReadParams contains all the parameters to send to the API endpoint
for the pull request comments read operation typically these are written to a http.Request
*/
type PullRequestCommentsReadParams struct {

	/*ID
	  A unique integer value identifying this pr comment.

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the pull request comments read params
func (o *PullRequestCommentsReadParams) WithTimeout(timeout time.Duration) *PullRequestCommentsReadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the pull request comments read params
func (o *PullRequestCommentsReadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the pull request comments read params
func (o *PullRequestCommentsReadParams) WithContext(ctx context.Context) *PullRequestCommentsReadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the pull request comments read params
func (o *PullRequestCommentsReadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the pull request comments read params
func (o *PullRequestCommentsReadParams) WithHTTPClient(client *http.Client) *PullRequestCommentsReadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the pull request comments read params
func (o *PullRequestCommentsReadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the pull request comments read params
func (o *PullRequestCommentsReadParams) WithID(id int64) *PullRequestCommentsReadParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the pull request comments read params
func (o *PullRequestCommentsReadParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PullRequestCommentsReadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
