// Code generated by go-swagger; DO NOT EDIT.

package tags

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TagsAddTagsReader is a Reader for the TagsAddTags structure.
type TagsAddTagsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TagsAddTagsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewTagsAddTagsCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewTagsAddTagsCreated creates a TagsAddTagsCreated with default headers values
func NewTagsAddTagsCreated() *TagsAddTagsCreated {
	return &TagsAddTagsCreated{}
}

/*TagsAddTagsCreated handles this case with default header values.

TagsAddTagsCreated tags add tags created
*/
type TagsAddTagsCreated struct {
	Payload interface{}
}

func (o *TagsAddTagsCreated) Error() string {
	return fmt.Sprintf("[POST /v3/customer/core/tags/add_tags/][%d] tagsAddTagsCreated  %+v", 201, o.Payload)
}

func (o *TagsAddTagsCreated) GetPayload() interface{} {
	return o.Payload
}

func (o *TagsAddTagsCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*TagsAddTagsBody tags add tags body
swagger:model TagsAddTagsBody
*/
type TagsAddTagsBody struct {

	// repo ids
	// Required: true
	RepoIds []string `json:"repo_ids"`

	// tag ids
	// Required: true
	TagIds []string `json:"tag_ids"`
}

// Validate validates this tags add tags body
func (o *TagsAddTagsBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateRepoIds(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateTagIds(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *TagsAddTagsBody) validateRepoIds(formats strfmt.Registry) error {

	if err := validate.Required("data"+"."+"repo_ids", "body", o.RepoIds); err != nil {
		return err
	}

	return nil
}

func (o *TagsAddTagsBody) validateTagIds(formats strfmt.Registry) error {

	if err := validate.Required("data"+"."+"tag_ids", "body", o.TagIds); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *TagsAddTagsBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *TagsAddTagsBody) UnmarshalBinary(b []byte) error {
	var res TagsAddTagsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
