// Code generated by go-swagger; DO NOT EDIT.

package tags

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewTagsCreateParams creates a new TagsCreateParams object
// with the default values initialized.
func NewTagsCreateParams() *TagsCreateParams {
	var ()
	return &TagsCreateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewTagsCreateParamsWithTimeout creates a new TagsCreateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewTagsCreateParamsWithTimeout(timeout time.Duration) *TagsCreateParams {
	var ()
	return &TagsCreateParams{

		timeout: timeout,
	}
}

// NewTagsCreateParamsWithContext creates a new TagsCreateParams object
// with the default values initialized, and the ability to set a context for a request
func NewTagsCreateParamsWithContext(ctx context.Context) *TagsCreateParams {
	var ()
	return &TagsCreateParams{

		Context: ctx,
	}
}

// NewTagsCreateParamsWithHTTPClient creates a new TagsCreateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewTagsCreateParamsWithHTTPClient(client *http.Client) *TagsCreateParams {
	var ()
	return &TagsCreateParams{
		HTTPClient: client,
	}
}

/*TagsCreateParams contains all the parameters to send to the API endpoint
for the tags create operation typically these are written to a http.Request
*/
type TagsCreateParams struct {

	/*Data*/
	Data TagsCreateBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the tags create params
func (o *TagsCreateParams) WithTimeout(timeout time.Duration) *TagsCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the tags create params
func (o *TagsCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the tags create params
func (o *TagsCreateParams) WithContext(ctx context.Context) *TagsCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the tags create params
func (o *TagsCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the tags create params
func (o *TagsCreateParams) WithHTTPClient(client *http.Client) *TagsCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the tags create params
func (o *TagsCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the tags create params
func (o *TagsCreateParams) WithData(data TagsCreateBody) *TagsCreateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the tags create params
func (o *TagsCreateParams) SetData(data TagsCreateBody) {
	o.Data = data
}

// WriteToRequest writes these params to a swagger request
func (o *TagsCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Data); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
