// Code generated by go-swagger; DO NOT EDIT.

package tags

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewTagsReadParams creates a new TagsReadParams object
// with the default values initialized.
func NewTagsReadParams() *TagsReadParams {
	var ()
	return &TagsReadParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewTagsReadParamsWithTimeout creates a new TagsReadParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewTagsReadParamsWithTimeout(timeout time.Duration) *TagsReadParams {
	var ()
	return &TagsReadParams{

		timeout: timeout,
	}
}

// NewTagsReadParamsWithContext creates a new TagsReadParams object
// with the default values initialized, and the ability to set a context for a request
func NewTagsReadParamsWithContext(ctx context.Context) *TagsReadParams {
	var ()
	return &TagsReadParams{

		Context: ctx,
	}
}

// NewTagsReadParamsWithHTTPClient creates a new TagsReadParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewTagsReadParamsWithHTTPClient(client *http.Client) *TagsReadParams {
	var ()
	return &TagsReadParams{
		HTTPClient: client,
	}
}

/*TagsReadParams contains all the parameters to send to the API endpoint
for the tags read operation typically these are written to a http.Request
*/
type TagsReadParams struct {

	/*ID
	  A unique integer value identifying this tag.

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the tags read params
func (o *TagsReadParams) WithTimeout(timeout time.Duration) *TagsReadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the tags read params
func (o *TagsReadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the tags read params
func (o *TagsReadParams) WithContext(ctx context.Context) *TagsReadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the tags read params
func (o *TagsReadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the tags read params
func (o *TagsReadParams) WithHTTPClient(client *http.Client) *TagsReadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the tags read params
func (o *TagsReadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the tags read params
func (o *TagsReadParams) WithID(id int64) *TagsReadParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the tags read params
func (o *TagsReadParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *TagsReadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
