// Code generated by go-swagger; DO NOT EDIT.

package tickets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewTicketsReadParams creates a new TicketsReadParams object
// with the default values initialized.
func NewTicketsReadParams() *TicketsReadParams {
	var ()
	return &TicketsReadParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewTicketsReadParamsWithTimeout creates a new TicketsReadParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewTicketsReadParamsWithTimeout(timeout time.Duration) *TicketsReadParams {
	var ()
	return &TicketsReadParams{

		timeout: timeout,
	}
}

// NewTicketsReadParamsWithContext creates a new TicketsReadParams object
// with the default values initialized, and the ability to set a context for a request
func NewTicketsReadParamsWithContext(ctx context.Context) *TicketsReadParams {
	var ()
	return &TicketsReadParams{

		Context: ctx,
	}
}

// NewTicketsReadParamsWithHTTPClient creates a new TicketsReadParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewTicketsReadParamsWithHTTPClient(client *http.Client) *TicketsReadParams {
	var ()
	return &TicketsReadParams{
		HTTPClient: client,
	}
}

/*TicketsReadParams contains all the parameters to send to the API endpoint
for the tickets read operation typically these are written to a http.Request
*/
type TicketsReadParams struct {

	/*ID
	  A unique integer value identifying this ticket.

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the tickets read params
func (o *TicketsReadParams) WithTimeout(timeout time.Duration) *TicketsReadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the tickets read params
func (o *TicketsReadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the tickets read params
func (o *TicketsReadParams) WithContext(ctx context.Context) *TicketsReadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the tickets read params
func (o *TicketsReadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the tickets read params
func (o *TicketsReadParams) WithHTTPClient(client *http.Client) *TicketsReadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the tickets read params
func (o *TicketsReadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the tickets read params
func (o *TicketsReadParams) WithID(id int64) *TicketsReadParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the tickets read params
func (o *TicketsReadParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *TicketsReadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
