// Code generated by go-swagger; DO NOT EDIT.

package tickets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new tickets API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for tickets API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	TicketsList(params *TicketsListParams, authInfo runtime.ClientAuthInfoWriter) (*TicketsListOK, error)

	TicketsRead(params *TicketsReadParams, authInfo runtime.ClientAuthInfoWriter) (*TicketsReadOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  TicketsList lists ticket entities

  List Ticket entities

--- Ticket ---

A Ticket is a specific issue filed by an author within integrated issue-tracking software.

--- General ---

All objects can be traversed to related objects. This can be achieved by using the double-underscore syntax.
For instance, query all Author records with a specific Team name like so:

"?team\_\_name=Bobs%20Team".

You can easily traverse multiple levels of relationships by connecting related objects. For example:

"?foo\_\_bar\_\_baz\_\_name=Bob"

All available relationships are defined in the filter documentation with the note "filter-traversable object."
Additionally, you can limit the properties returned in an object by using the `fields` or `omit`
keywords as follows:

"?fields=foo,bar,bad" will return only these fields

or

"?omit=foo,bar,baz" will return all but the specified fields
*/
func (a *Client) TicketsList(params *TicketsListParams, authInfo runtime.ClientAuthInfoWriter) (*TicketsListOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewTicketsListParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "tickets_list",
		Method:             "GET",
		PathPattern:        "/v3/customer/core/tickets/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &TicketsListReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*TicketsListOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for tickets_list: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  TicketsRead gets a specific ticket entity by id value

  Get a specific Ticket entity by id value
*/
func (a *Client) TicketsRead(params *TicketsReadParams, authInfo runtime.ClientAuthInfoWriter) (*TicketsReadOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewTicketsReadParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "tickets_read",
		Method:             "GET",
		PathPattern:        "/v3/customer/core/tickets/{id}/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &TicketsReadReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*TicketsReadOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for tickets_read: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
