// Code generated by go-swagger; DO NOT EDIT.

package tickets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// TicketsReadReader is a Reader for the TicketsRead structure.
type TicketsReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TicketsReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewTicketsReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewTicketsReadOK creates a TicketsReadOK with default headers values
func NewTicketsReadOK() *TicketsReadOK {
	return &TicketsReadOK{}
}

/*TicketsReadOK handles this case with default header values.

TicketsReadOK tickets read o k
*/
type TicketsReadOK struct {
	Payload interface{}
}

func (o *TicketsReadOK) Error() string {
	return fmt.Sprintf("[GET /v3/customer/core/tickets/{id}/][%d] ticketsReadOK  %+v", 200, o.Payload)
}

func (o *TicketsReadOK) GetPayload() interface{} {
	return o.Payload
}

func (o *TicketsReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
