// Code generated by go-swagger; DO NOT EDIT.

package pull_request_projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new pull request projects API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for pull request projects API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	PullRequestProjectsList(params *PullRequestProjectsListParams, authInfo runtime.ClientAuthInfoWriter) (*PullRequestProjectsListOK, error)

	PullRequestProjectsRead(params *PullRequestProjectsReadParams, authInfo runtime.ClientAuthInfoWriter) (*PullRequestProjectsReadOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  PullRequestProjectsList lists project entities

  List Project entities

--- Pull Request Project ---

A Pull Request Project represent an entity that is the recipient of pull requests. All pull requests
are tied to a Pull Request Project. Typically all Pull Request Projects are also bound to a repository, which are
discovered using a user's credentials.

--- General ---

All objects can be traversed to related objects. This can be achieved by using the double-underscore syntax.
For instance, query all Author records with a specific Team name like so:

"?team\_\_name=Bobs%20Team".

You can easily traverse multiple levels of relationships by connecting related objects. For example:

"?foo\_\_bar\_\_baz\_\_name=Bob"

All available relationships are defined in the filter documentation with the note "filter-traversable object."
Additionally, you can limit the properties returned in an object by using the `fields` or `omit`
keywords as follows:

"?fields=foo,bar,bad" will return only these fields

or

"?omit=foo,bar,baz" will return all but the specified fields
*/
func (a *Client) PullRequestProjectsList(params *PullRequestProjectsListParams, authInfo runtime.ClientAuthInfoWriter) (*PullRequestProjectsListOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPullRequestProjectsListParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "pull_request_projects_list",
		Method:             "GET",
		PathPattern:        "/v3/customer/core/pull_request_projects/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PullRequestProjectsListReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PullRequestProjectsListOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for pull_request_projects_list: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  PullRequestProjectsRead gets a specific project pull request entity by id value

  Get a specific ProjectPullRequest entity by id value
*/
func (a *Client) PullRequestProjectsRead(params *PullRequestProjectsReadParams, authInfo runtime.ClientAuthInfoWriter) (*PullRequestProjectsReadOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPullRequestProjectsReadParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "pull_request_projects_read",
		Method:             "GET",
		PathPattern:        "/v3/customer/core/pull_request_projects/{id}/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PullRequestProjectsReadReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PullRequestProjectsReadOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for pull_request_projects_read: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
