// Code generated by go-swagger; DO NOT EDIT.

package targets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// TargetsListReader is a Reader for the TargetsList structure.
type TargetsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TargetsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewTargetsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewTargetsListOK creates a TargetsListOK with default headers values
func NewTargetsListOK() *TargetsListOK {
	return &TargetsListOK{}
}

/*TargetsListOK handles this case with default header values.

TargetsListOK targets list o k
*/
type TargetsListOK struct {
	Payload interface{}
}

func (o *TargetsListOK) Error() string {
	return fmt.Sprintf("[GET /v3/customer/core/targets/][%d] targetsListOK  %+v", 200, o.Payload)
}

func (o *TargetsListOK) GetPayload() interface{} {
	return o.Payload
}

func (o *TargetsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
