// Code generated by go-swagger; DO NOT EDIT.

package ticket_comments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewTicketCommentsReadParams creates a new TicketCommentsReadParams object
// with the default values initialized.
func NewTicketCommentsReadParams() *TicketCommentsReadParams {
	var ()
	return &TicketCommentsReadParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewTicketCommentsReadParamsWithTimeout creates a new TicketCommentsReadParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewTicketCommentsReadParamsWithTimeout(timeout time.Duration) *TicketCommentsReadParams {
	var ()
	return &TicketCommentsReadParams{

		timeout: timeout,
	}
}

// NewTicketCommentsReadParamsWithContext creates a new TicketCommentsReadParams object
// with the default values initialized, and the ability to set a context for a request
func NewTicketCommentsReadParamsWithContext(ctx context.Context) *TicketCommentsReadParams {
	var ()
	return &TicketCommentsReadParams{

		Context: ctx,
	}
}

// NewTicketCommentsReadParamsWithHTTPClient creates a new TicketCommentsReadParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewTicketCommentsReadParamsWithHTTPClient(client *http.Client) *TicketCommentsReadParams {
	var ()
	return &TicketCommentsReadParams{
		HTTPClient: client,
	}
}

/*TicketCommentsReadParams contains all the parameters to send to the API endpoint
for the ticket comments read operation typically these are written to a http.Request
*/
type TicketCommentsReadParams struct {

	/*ID
	  A unique integer value identifying this ticket comment.

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the ticket comments read params
func (o *TicketCommentsReadParams) WithTimeout(timeout time.Duration) *TicketCommentsReadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the ticket comments read params
func (o *TicketCommentsReadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the ticket comments read params
func (o *TicketCommentsReadParams) WithContext(ctx context.Context) *TicketCommentsReadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the ticket comments read params
func (o *TicketCommentsReadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the ticket comments read params
func (o *TicketCommentsReadParams) WithHTTPClient(client *http.Client) *TicketCommentsReadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the ticket comments read params
func (o *TicketCommentsReadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the ticket comments read params
func (o *TicketCommentsReadParams) WithID(id int64) *TicketCommentsReadParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the ticket comments read params
func (o *TicketCommentsReadParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *TicketCommentsReadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
