// Code generated by go-swagger; DO NOT EDIT.

package available_repos

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new available repos API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for available repos API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	AvailableReposList(params *AvailableReposListParams, authInfo runtime.ClientAuthInfoWriter) (*AvailableReposListOK, error)

	AvailableReposRead(params *AvailableReposReadParams, authInfo runtime.ClientAuthInfoWriter) (*AvailableReposReadOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  AvailableReposList lists all available repos

  List all available repos
*/
func (a *Client) AvailableReposList(params *AvailableReposListParams, authInfo runtime.ClientAuthInfoWriter) (*AvailableReposListOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewAvailableReposListParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "available_repos_list",
		Method:             "GET",
		PathPattern:        "/v3/customer/core/available_repos/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &AvailableReposListReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*AvailableReposListOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for available_repos_list: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  AvailableReposRead gets a specific available repo by id value

  Get a specific available repo by id value
*/
func (a *Client) AvailableReposRead(params *AvailableReposReadParams, authInfo runtime.ClientAuthInfoWriter) (*AvailableReposReadOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewAvailableReposReadParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "available_repos_read",
		Method:             "GET",
		PathPattern:        "/v3/customer/core/available_repos/{id}/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &AvailableReposReadReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*AvailableReposReadOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for available_repos_read: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
