// Code generated by go-swagger; DO NOT EDIT.

package available_repos

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// AvailableReposListReader is a Reader for the AvailableReposList structure.
type AvailableReposListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AvailableReposListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAvailableReposListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewAvailableReposListOK creates a AvailableReposListOK with default headers values
func NewAvailableReposListOK() *AvailableReposListOK {
	return &AvailableReposListOK{}
}

/*AvailableReposListOK handles this case with default header values.

AvailableReposListOK available repos list o k
*/
type AvailableReposListOK struct {
	Payload interface{}
}

func (o *AvailableReposListOK) Error() string {
	return fmt.Sprintf("[GET /v3/customer/core/available_repos/][%d] availableReposListOK  %+v", 200, o.Payload)
}

func (o *AvailableReposListOK) GetPayload() interface{} {
	return o.Payload
}

func (o *AvailableReposListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
