// Code generated by go-swagger; DO NOT EDIT.

package grants

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new grants API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for grants API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	GrantsList(params *GrantsListParams, authInfo runtime.ClientAuthInfoWriter) (*GrantsListOK, error)

	GrantsRead(params *GrantsReadParams, authInfo runtime.ClientAuthInfoWriter) (*GrantsReadOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  GrantsList lists grant entities

  List Grant entities

A Grant is a set of permissions that can be assigned to a member or role.

--- General ---

All objects can be traversed to related objects. This can be achieved by using the double-underscore syntax.
For instance, query all Author records with a specific Team name like so:

"?team\_\_name=Bobs%20Team".

You can easily traverse multiple levels of relationships by connecting related objects. For example:

"?foo\_\_bar\_\_baz\_\_name=Bob"

All available relationships are defined in the filter documentation with the note "filter-traversable object."
Additionally, you can limit the properties returned in an object by using the `fields` or `omit`
keywords as follows:

"?fields=foo,bar,bad" will return only these fields

or

"?omit=foo,bar,baz" will return all but the specified fields
*/
func (a *Client) GrantsList(params *GrantsListParams, authInfo runtime.ClientAuthInfoWriter) (*GrantsListOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGrantsListParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "grants_list",
		Method:             "GET",
		PathPattern:        "/v3/customer/core/grants/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GrantsListReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GrantsListOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for grants_list: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GrantsRead gets a specific grant entity by id value

  Get a specific Grant entity by id value
*/
func (a *Client) GrantsRead(params *GrantsReadParams, authInfo runtime.ClientAuthInfoWriter) (*GrantsReadOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGrantsReadParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "grants_read",
		Method:             "GET",
		PathPattern:        "/v3/customer/core/grants/{id}/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GrantsReadReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GrantsReadOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for grants_read: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
