// Code generated by go-swagger; DO NOT EDIT.

package grants

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGrantsListParams creates a new GrantsListParams object
// with the default values initialized.
func NewGrantsListParams() *GrantsListParams {
	var ()
	return &GrantsListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGrantsListParamsWithTimeout creates a new GrantsListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGrantsListParamsWithTimeout(timeout time.Duration) *GrantsListParams {
	var ()
	return &GrantsListParams{

		timeout: timeout,
	}
}

// NewGrantsListParamsWithContext creates a new GrantsListParams object
// with the default values initialized, and the ability to set a context for a request
func NewGrantsListParamsWithContext(ctx context.Context) *GrantsListParams {
	var ()
	return &GrantsListParams{

		Context: ctx,
	}
}

// NewGrantsListParamsWithHTTPClient creates a new GrantsListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGrantsListParamsWithHTTPClient(client *http.Client) *GrantsListParams {
	var ()
	return &GrantsListParams{
		HTTPClient: client,
	}
}

/*GrantsListParams contains all the parameters to send to the API endpoint
for the grants list operation typically these are written to a http.Request
*/
type GrantsListParams struct {

	/*Filters
	  Complex filter that handles filtering with groups of conditions connected with AND and OR conjunctions. The query can be arbitrarily grouped and nested.

	*/
	Filters *string
	/*ID*/
	ID *float64
	/*Limit
	  Number of results to return per page.

	*/
	Limit *int64
	/*Offset
	  The initial index from which to return the results.

	*/
	Offset *int64
	/*Ordering
	  Valid ordering fields are: `id`

	*/
	Ordering *string
	/*Search
	  A search term.

	*/
	Search *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the grants list params
func (o *GrantsListParams) WithTimeout(timeout time.Duration) *GrantsListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the grants list params
func (o *GrantsListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the grants list params
func (o *GrantsListParams) WithContext(ctx context.Context) *GrantsListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the grants list params
func (o *GrantsListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the grants list params
func (o *GrantsListParams) WithHTTPClient(client *http.Client) *GrantsListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the grants list params
func (o *GrantsListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFilters adds the filters to the grants list params
func (o *GrantsListParams) WithFilters(filters *string) *GrantsListParams {
	o.SetFilters(filters)
	return o
}

// SetFilters adds the filters to the grants list params
func (o *GrantsListParams) SetFilters(filters *string) {
	o.Filters = filters
}

// WithID adds the id to the grants list params
func (o *GrantsListParams) WithID(id *float64) *GrantsListParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the grants list params
func (o *GrantsListParams) SetID(id *float64) {
	o.ID = id
}

// WithLimit adds the limit to the grants list params
func (o *GrantsListParams) WithLimit(limit *int64) *GrantsListParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the grants list params
func (o *GrantsListParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithOffset adds the offset to the grants list params
func (o *GrantsListParams) WithOffset(offset *int64) *GrantsListParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the grants list params
func (o *GrantsListParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WithOrdering adds the ordering to the grants list params
func (o *GrantsListParams) WithOrdering(ordering *string) *GrantsListParams {
	o.SetOrdering(ordering)
	return o
}

// SetOrdering adds the ordering to the grants list params
func (o *GrantsListParams) SetOrdering(ordering *string) {
	o.Ordering = ordering
}

// WithSearch adds the search to the grants list params
func (o *GrantsListParams) WithSearch(search *string) *GrantsListParams {
	o.SetSearch(search)
	return o
}

// SetSearch adds the search to the grants list params
func (o *GrantsListParams) SetSearch(search *string) {
	o.Search = search
}

// WriteToRequest writes these params to a swagger request
func (o *GrantsListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Filters != nil {

		// query param filters
		var qrFilters string
		if o.Filters != nil {
			qrFilters = *o.Filters
		}
		qFilters := qrFilters
		if qFilters != "" {
			if err := r.SetQueryParam("filters", qFilters); err != nil {
				return err
			}
		}

	}

	if o.ID != nil {

		// query param id
		var qrID float64
		if o.ID != nil {
			qrID = *o.ID
		}
		qID := swag.FormatFloat64(qrID)
		if qID != "" {
			if err := r.SetQueryParam("id", qID); err != nil {
				return err
			}
		}

	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	if o.Ordering != nil {

		// query param ordering
		var qrOrdering string
		if o.Ordering != nil {
			qrOrdering = *o.Ordering
		}
		qOrdering := qrOrdering
		if qOrdering != "" {
			if err := r.SetQueryParam("ordering", qOrdering); err != nil {
				return err
			}
		}

	}

	if o.Search != nil {

		// query param search
		var qrSearch string
		if o.Search != nil {
			qrSearch = *o.Search
		}
		qSearch := qrSearch
		if qSearch != "" {
			if err := r.SetQueryParam("search", qSearch); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
