// Code generated by go-swagger; DO NOT EDIT.

package integrations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewIntegrationsManualHTTPSCreateParams creates a new IntegrationsManualHTTPSCreateParams object
// with the default values initialized.
func NewIntegrationsManualHTTPSCreateParams() *IntegrationsManualHTTPSCreateParams {
	var ()
	return &IntegrationsManualHTTPSCreateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewIntegrationsManualHTTPSCreateParamsWithTimeout creates a new IntegrationsManualHTTPSCreateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewIntegrationsManualHTTPSCreateParamsWithTimeout(timeout time.Duration) *IntegrationsManualHTTPSCreateParams {
	var ()
	return &IntegrationsManualHTTPSCreateParams{

		timeout: timeout,
	}
}

// NewIntegrationsManualHTTPSCreateParamsWithContext creates a new IntegrationsManualHTTPSCreateParams object
// with the default values initialized, and the ability to set a context for a request
func NewIntegrationsManualHTTPSCreateParamsWithContext(ctx context.Context) *IntegrationsManualHTTPSCreateParams {
	var ()
	return &IntegrationsManualHTTPSCreateParams{

		Context: ctx,
	}
}

// NewIntegrationsManualHTTPSCreateParamsWithHTTPClient creates a new IntegrationsManualHTTPSCreateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewIntegrationsManualHTTPSCreateParamsWithHTTPClient(client *http.Client) *IntegrationsManualHTTPSCreateParams {
	var ()
	return &IntegrationsManualHTTPSCreateParams{
		HTTPClient: client,
	}
}

/*IntegrationsManualHTTPSCreateParams contains all the parameters to send to the API endpoint
for the integrations manual https create operation typically these are written to a http.Request
*/
type IntegrationsManualHTTPSCreateParams struct {

	/*Data*/
	Data IntegrationsManualHTTPSCreateBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the integrations manual https create params
func (o *IntegrationsManualHTTPSCreateParams) WithTimeout(timeout time.Duration) *IntegrationsManualHTTPSCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the integrations manual https create params
func (o *IntegrationsManualHTTPSCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the integrations manual https create params
func (o *IntegrationsManualHTTPSCreateParams) WithContext(ctx context.Context) *IntegrationsManualHTTPSCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the integrations manual https create params
func (o *IntegrationsManualHTTPSCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the integrations manual https create params
func (o *IntegrationsManualHTTPSCreateParams) WithHTTPClient(client *http.Client) *IntegrationsManualHTTPSCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the integrations manual https create params
func (o *IntegrationsManualHTTPSCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the integrations manual https create params
func (o *IntegrationsManualHTTPSCreateParams) WithData(data IntegrationsManualHTTPSCreateBody) *IntegrationsManualHTTPSCreateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the integrations manual https create params
func (o *IntegrationsManualHTTPSCreateParams) SetData(data IntegrationsManualHTTPSCreateBody) {
	o.Data = data
}

// WriteToRequest writes these params to a swagger request
func (o *IntegrationsManualHTTPSCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Data); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
