// Code generated by go-swagger; DO NOT EDIT.

package integrations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// IntegrationsListReader is a Reader for the IntegrationsList structure.
type IntegrationsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IntegrationsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewIntegrationsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewIntegrationsListOK creates a IntegrationsListOK with default headers values
func NewIntegrationsListOK() *IntegrationsListOK {
	return &IntegrationsListOK{}
}

/*IntegrationsListOK handles this case with default header values.

IntegrationsListOK integrations list o k
*/
type IntegrationsListOK struct {
	Payload interface{}
}

func (o *IntegrationsListOK) Error() string {
	return fmt.Sprintf("[GET /v3/customer/core/integrations/][%d] integrationsListOK  %+v", 200, o.Payload)
}

func (o *IntegrationsListOK) GetPayload() interface{} {
	return o.Payload
}

func (o *IntegrationsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
