// Code generated by go-swagger; DO NOT EDIT.

package integrations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// IntegrationsManualHTTPSCreateReader is a Reader for the IntegrationsManualHTTPSCreate structure.
type IntegrationsManualHTTPSCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IntegrationsManualHTTPSCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewIntegrationsManualHTTPSCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewIntegrationsManualHTTPSCreateCreated creates a IntegrationsManualHTTPSCreateCreated with default headers values
func NewIntegrationsManualHTTPSCreateCreated() *IntegrationsManualHTTPSCreateCreated {
	return &IntegrationsManualHTTPSCreateCreated{}
}

/*IntegrationsManualHTTPSCreateCreated handles this case with default header values.

IntegrationsManualHTTPSCreateCreated integrations manual Https create created
*/
type IntegrationsManualHTTPSCreateCreated struct {
	Payload interface{}
}

func (o *IntegrationsManualHTTPSCreateCreated) Error() string {
	return fmt.Sprintf("[POST /v3/customer/core/integrations/manual_https_create/][%d] integrationsManualHttpsCreateCreated  %+v", 201, o.Payload)
}

func (o *IntegrationsManualHTTPSCreateCreated) GetPayload() interface{} {
	return o.Payload
}

func (o *IntegrationsManualHTTPSCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*IntegrationsManualHTTPSCreateBody integrations manual HTTPS create body
swagger:model IntegrationsManualHTTPSCreateBody
*/
type IntegrationsManualHTTPSCreateBody struct {

	// enabled services
	// Required: true
	EnabledServices []string `json:"enabled_services"`

	// name
	// Required: true
	Name *string `json:"name"`

	// password
	Password string `json:"password,omitempty"`

	// url
	URL string `json:"url,omitempty"`

	// username
	Username string `json:"username,omitempty"`
}

// Validate validates this integrations manual HTTPS create body
func (o *IntegrationsManualHTTPSCreateBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateEnabledServices(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *IntegrationsManualHTTPSCreateBody) validateEnabledServices(formats strfmt.Registry) error {

	if err := validate.Required("data"+"."+"enabled_services", "body", o.EnabledServices); err != nil {
		return err
	}

	return nil
}

func (o *IntegrationsManualHTTPSCreateBody) validateName(formats strfmt.Registry) error {

	if err := validate.Required("data"+"."+"name", "body", o.Name); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *IntegrationsManualHTTPSCreateBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *IntegrationsManualHTTPSCreateBody) UnmarshalBinary(b []byte) error {
	var res IntegrationsManualHTTPSCreateBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
