// Code generated by go-swagger; DO NOT EDIT.

package integrations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewIntegrationsCreateWithVendorParams creates a new IntegrationsCreateWithVendorParams object
// with the default values initialized.
func NewIntegrationsCreateWithVendorParams() *IntegrationsCreateWithVendorParams {
	var ()
	return &IntegrationsCreateWithVendorParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewIntegrationsCreateWithVendorParamsWithTimeout creates a new IntegrationsCreateWithVendorParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewIntegrationsCreateWithVendorParamsWithTimeout(timeout time.Duration) *IntegrationsCreateWithVendorParams {
	var ()
	return &IntegrationsCreateWithVendorParams{

		timeout: timeout,
	}
}

// NewIntegrationsCreateWithVendorParamsWithContext creates a new IntegrationsCreateWithVendorParams object
// with the default values initialized, and the ability to set a context for a request
func NewIntegrationsCreateWithVendorParamsWithContext(ctx context.Context) *IntegrationsCreateWithVendorParams {
	var ()
	return &IntegrationsCreateWithVendorParams{

		Context: ctx,
	}
}

// NewIntegrationsCreateWithVendorParamsWithHTTPClient creates a new IntegrationsCreateWithVendorParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewIntegrationsCreateWithVendorParamsWithHTTPClient(client *http.Client) *IntegrationsCreateWithVendorParams {
	var ()
	return &IntegrationsCreateWithVendorParams{
		HTTPClient: client,
	}
}

/*IntegrationsCreateWithVendorParams contains all the parameters to send to the API endpoint
for the integrations create with vendor operation typically these are written to a http.Request
*/
type IntegrationsCreateWithVendorParams struct {

	/*Data*/
	Data IntegrationsCreateWithVendorBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the integrations create with vendor params
func (o *IntegrationsCreateWithVendorParams) WithTimeout(timeout time.Duration) *IntegrationsCreateWithVendorParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the integrations create with vendor params
func (o *IntegrationsCreateWithVendorParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the integrations create with vendor params
func (o *IntegrationsCreateWithVendorParams) WithContext(ctx context.Context) *IntegrationsCreateWithVendorParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the integrations create with vendor params
func (o *IntegrationsCreateWithVendorParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the integrations create with vendor params
func (o *IntegrationsCreateWithVendorParams) WithHTTPClient(client *http.Client) *IntegrationsCreateWithVendorParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the integrations create with vendor params
func (o *IntegrationsCreateWithVendorParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the integrations create with vendor params
func (o *IntegrationsCreateWithVendorParams) WithData(data IntegrationsCreateWithVendorBody) *IntegrationsCreateWithVendorParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the integrations create with vendor params
func (o *IntegrationsCreateWithVendorParams) SetData(data IntegrationsCreateWithVendorBody) {
	o.Data = data
}

// WriteToRequest writes these params to a swagger request
func (o *IntegrationsCreateWithVendorParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Data); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
