// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UsersCreateReader is a Reader for the UsersCreate structure.
type UsersCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UsersCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewUsersCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUsersCreateCreated creates a UsersCreateCreated with default headers values
func NewUsersCreateCreated() *UsersCreateCreated {
	return &UsersCreateCreated{}
}

/*UsersCreateCreated handles this case with default header values.

UsersCreateCreated users create created
*/
type UsersCreateCreated struct {
	Payload interface{}
}

func (o *UsersCreateCreated) Error() string {
	return fmt.Sprintf("[POST /v3/customer/core/users/][%d] usersCreateCreated  %+v", 201, o.Payload)
}

func (o *UsersCreateCreated) GetPayload() interface{} {
	return o.Payload
}

func (o *UsersCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*UsersCreateBody users create body
swagger:model UsersCreateBody
*/
type UsersCreateBody struct {

	// created at
	CreatedAt string `json:"created_at,omitempty"`

	// email
	Email string `json:"email,omitempty"`

	// first activity at
	FirstActivityAt string `json:"first_activity_at,omitempty"`

	// hidden from reports
	HiddenFromReports bool `json:"hidden_from_reports,omitempty"`

	// last activity at
	LastActivityAt string `json:"last_activity_at,omitempty"`

	// login
	// Required: true
	Login interface{} `json:"login"`

	// name
	Name string `json:"name,omitempty"`

	// team ids
	TeamIds []string `json:"team_ids"`
}

// Validate validates this users create body
func (o *UsersCreateBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateLogin(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *UsersCreateBody) validateLogin(formats strfmt.Registry) error {

	if err := validate.Required("data"+"."+"login", "body", o.Login); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *UsersCreateBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UsersCreateBody) UnmarshalBinary(b []byte) error {
	var res UsersCreateBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
