// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UsersLoginPartialUpdateReader is a Reader for the UsersLoginPartialUpdate structure.
type UsersLoginPartialUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UsersLoginPartialUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUsersLoginPartialUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUsersLoginPartialUpdateOK creates a UsersLoginPartialUpdateOK with default headers values
func NewUsersLoginPartialUpdateOK() *UsersLoginPartialUpdateOK {
	return &UsersLoginPartialUpdateOK{}
}

/*UsersLoginPartialUpdateOK handles this case with default header values.

UsersLoginPartialUpdateOK users login partial update o k
*/
type UsersLoginPartialUpdateOK struct {
	Payload interface{}
}

func (o *UsersLoginPartialUpdateOK) Error() string {
	return fmt.Sprintf("[PATCH /v3/customer/core/users/{id}/login/][%d] usersLoginPartialUpdateOK  %+v", 200, o.Payload)
}

func (o *UsersLoginPartialUpdateOK) GetPayload() interface{} {
	return o.Payload
}

func (o *UsersLoginPartialUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*UsersLoginPartialUpdateBody users login partial update body
swagger:model UsersLoginPartialUpdateBody
*/
type UsersLoginPartialUpdateBody struct {

	// access ids
	AccessIds []string `json:"access_ids"`

	// login email
	LoginEmail string `json:"login_email,omitempty"`

	// Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
	LoginEnabled bool `json:"login_enabled,omitempty"`

	// login preferred name
	LoginPreferredName string `json:"login_preferred_name,omitempty"`

	// needs password reset
	NeedsPasswordReset bool `json:"needs_password_reset,omitempty"`

	// role ids
	RoleIds []string `json:"role_ids"`

	// team visibility
	TeamVisibility string `json:"team_visibility,omitempty"`

	// user visibility
	UserVisibility string `json:"user_visibility,omitempty"`
}

// Validate validates this users login partial update body
func (o *UsersLoginPartialUpdateBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *UsersLoginPartialUpdateBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UsersLoginPartialUpdateBody) UnmarshalBinary(b []byte) error {
	var res UsersLoginPartialUpdateBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
