// Code generated by go-swagger; DO NOT EDIT.

package user_alias

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewUserAliasReadParams creates a new UserAliasReadParams object
// with the default values initialized.
func NewUserAliasReadParams() *UserAliasReadParams {
	var ()
	return &UserAliasReadParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUserAliasReadParamsWithTimeout creates a new UserAliasReadParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUserAliasReadParamsWithTimeout(timeout time.Duration) *UserAliasReadParams {
	var ()
	return &UserAliasReadParams{

		timeout: timeout,
	}
}

// NewUserAliasReadParamsWithContext creates a new UserAliasReadParams object
// with the default values initialized, and the ability to set a context for a request
func NewUserAliasReadParamsWithContext(ctx context.Context) *UserAliasReadParams {
	var ()
	return &UserAliasReadParams{

		Context: ctx,
	}
}

// NewUserAliasReadParamsWithHTTPClient creates a new UserAliasReadParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUserAliasReadParamsWithHTTPClient(client *http.Client) *UserAliasReadParams {
	var ()
	return &UserAliasReadParams{
		HTTPClient: client,
	}
}

/*UserAliasReadParams contains all the parameters to send to the API endpoint
for the user alias read operation typically these are written to a http.Request
*/
type UserAliasReadParams struct {

	/*ID
	  A unique integer value identifying this user alias.

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the user alias read params
func (o *UserAliasReadParams) WithTimeout(timeout time.Duration) *UserAliasReadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the user alias read params
func (o *UserAliasReadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the user alias read params
func (o *UserAliasReadParams) WithContext(ctx context.Context) *UserAliasReadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the user alias read params
func (o *UserAliasReadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the user alias read params
func (o *UserAliasReadParams) WithHTTPClient(client *http.Client) *UserAliasReadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the user alias read params
func (o *UserAliasReadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the user alias read params
func (o *UserAliasReadParams) WithID(id int64) *UserAliasReadParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the user alias read params
func (o *UserAliasReadParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UserAliasReadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
