// Code generated by go-swagger; DO NOT EDIT.

package commits

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CommitsListReader is a Reader for the CommitsList structure.
type CommitsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CommitsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCommitsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCommitsListOK creates a CommitsListOK with default headers values
func NewCommitsListOK() *CommitsListOK {
	return &CommitsListOK{}
}

/*CommitsListOK handles this case with default header values.

CommitsListOK commits list o k
*/
type CommitsListOK struct {
	Payload interface{}
}

func (o *CommitsListOK) Error() string {
	return fmt.Sprintf("[GET /v3/customer/core/commits/][%d] commitsListOK  %+v", 200, o.Payload)
}

func (o *CommitsListOK) GetPayload() interface{} {
	return o.Payload
}

func (o *CommitsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
