// Code generated by go-swagger; DO NOT EDIT.

package team_membership

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TeamMembershipCreateReader is a Reader for the TeamMembershipCreate structure.
type TeamMembershipCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TeamMembershipCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewTeamMembershipCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewTeamMembershipCreateCreated creates a TeamMembershipCreateCreated with default headers values
func NewTeamMembershipCreateCreated() *TeamMembershipCreateCreated {
	return &TeamMembershipCreateCreated{}
}

/*TeamMembershipCreateCreated handles this case with default header values.

TeamMembershipCreateCreated team membership create created
*/
type TeamMembershipCreateCreated struct {
	Payload interface{}
}

func (o *TeamMembershipCreateCreated) Error() string {
	return fmt.Sprintf("[POST /v3/customer/core/team_membership/][%d] teamMembershipCreateCreated  %+v", 201, o.Payload)
}

func (o *TeamMembershipCreateCreated) GetPayload() interface{} {
	return o.Payload
}

func (o *TeamMembershipCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*TeamMembershipCreateBody team membership create body
swagger:model TeamMembershipCreateBody
*/
type TeamMembershipCreateBody struct {

	// apex user id
	// Required: true
	ApexUserID *int64 `json:"apex_user_id"`

	// depth
	// Required: true
	Depth *string `json:"depth"`

	// membership type
	MembershipType string `json:"membership_type,omitempty"`

	// team id
	// Required: true
	TeamID *int64 `json:"team_id"`
}

// Validate validates this team membership create body
func (o *TeamMembershipCreateBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateApexUserID(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateDepth(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateTeamID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *TeamMembershipCreateBody) validateApexUserID(formats strfmt.Registry) error {

	if err := validate.Required("data"+"."+"apex_user_id", "body", o.ApexUserID); err != nil {
		return err
	}

	return nil
}

func (o *TeamMembershipCreateBody) validateDepth(formats strfmt.Registry) error {

	if err := validate.Required("data"+"."+"depth", "body", o.Depth); err != nil {
		return err
	}

	return nil
}

func (o *TeamMembershipCreateBody) validateTeamID(formats strfmt.Registry) error {

	if err := validate.Required("data"+"."+"team_id", "body", o.TeamID); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *TeamMembershipCreateBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *TeamMembershipCreateBody) UnmarshalBinary(b []byte) error {
	var res TeamMembershipCreateBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
