// Code generated by go-swagger; DO NOT EDIT.

package teams

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// TeamsDeleteReader is a Reader for the TeamsDelete structure.
type TeamsDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TeamsDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewTeamsDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewTeamsDeleteNoContent creates a TeamsDeleteNoContent with default headers values
func NewTeamsDeleteNoContent() *TeamsDeleteNoContent {
	return &TeamsDeleteNoContent{}
}

/*TeamsDeleteNoContent handles this case with default header values.

TeamsDeleteNoContent teams delete no content
*/
type TeamsDeleteNoContent struct {
	Payload interface{}
}

func (o *TeamsDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /v3/customer/core/teams/{id}/][%d] teamsDeleteNoContent  %+v", 204, o.Payload)
}

func (o *TeamsDeleteNoContent) GetPayload() interface{} {
	return o.Payload
}

func (o *TeamsDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
