// Code generated by go-swagger; DO NOT EDIT.

package teams

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// TeamsListReader is a Reader for the TeamsList structure.
type TeamsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TeamsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewTeamsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewTeamsListOK creates a TeamsListOK with default headers values
func NewTeamsListOK() *TeamsListOK {
	return &TeamsListOK{}
}

/*TeamsListOK handles this case with default header values.

TeamsListOK teams list o k
*/
type TeamsListOK struct {
	Payload interface{}
}

func (o *TeamsListOK) Error() string {
	return fmt.Sprintf("[GET /v3/customer/core/teams/][%d] teamsListOK  %+v", 200, o.Payload)
}

func (o *TeamsListOK) GetPayload() interface{} {
	return o.Payload
}

func (o *TeamsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
