// Code generated by go-swagger; DO NOT EDIT.

package repos

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewReposImportRepoParams creates a new ReposImportRepoParams object
// with the default values initialized.
func NewReposImportRepoParams() *ReposImportRepoParams {
	var ()
	return &ReposImportRepoParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewReposImportRepoParamsWithTimeout creates a new ReposImportRepoParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewReposImportRepoParamsWithTimeout(timeout time.Duration) *ReposImportRepoParams {
	var ()
	return &ReposImportRepoParams{

		timeout: timeout,
	}
}

// NewReposImportRepoParamsWithContext creates a new ReposImportRepoParams object
// with the default values initialized, and the ability to set a context for a request
func NewReposImportRepoParamsWithContext(ctx context.Context) *ReposImportRepoParams {
	var ()
	return &ReposImportRepoParams{

		Context: ctx,
	}
}

// NewReposImportRepoParamsWithHTTPClient creates a new ReposImportRepoParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewReposImportRepoParamsWithHTTPClient(client *http.Client) *ReposImportRepoParams {
	var ()
	return &ReposImportRepoParams{
		HTTPClient: client,
	}
}

/*ReposImportRepoParams contains all the parameters to send to the API endpoint
for the repos import repo operation typically these are written to a http.Request
*/
type ReposImportRepoParams struct {

	/*Data*/
	Data ReposImportRepoBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the repos import repo params
func (o *ReposImportRepoParams) WithTimeout(timeout time.Duration) *ReposImportRepoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the repos import repo params
func (o *ReposImportRepoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the repos import repo params
func (o *ReposImportRepoParams) WithContext(ctx context.Context) *ReposImportRepoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the repos import repo params
func (o *ReposImportRepoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the repos import repo params
func (o *ReposImportRepoParams) WithHTTPClient(client *http.Client) *ReposImportRepoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the repos import repo params
func (o *ReposImportRepoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the repos import repo params
func (o *ReposImportRepoParams) WithData(data ReposImportRepoBody) *ReposImportRepoParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the repos import repo params
func (o *ReposImportRepoParams) SetData(data ReposImportRepoBody) {
	o.Data = data
}

// WriteToRequest writes these params to a swagger request
func (o *ReposImportRepoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Data); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
