// Code generated by go-swagger; DO NOT EDIT.

package repos

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewReposUpdateRepoParams creates a new ReposUpdateRepoParams object
// with the default values initialized.
func NewReposUpdateRepoParams() *ReposUpdateRepoParams {
	var ()
	return &ReposUpdateRepoParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewReposUpdateRepoParamsWithTimeout creates a new ReposUpdateRepoParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewReposUpdateRepoParamsWithTimeout(timeout time.Duration) *ReposUpdateRepoParams {
	var ()
	return &ReposUpdateRepoParams{

		timeout: timeout,
	}
}

// NewReposUpdateRepoParamsWithContext creates a new ReposUpdateRepoParams object
// with the default values initialized, and the ability to set a context for a request
func NewReposUpdateRepoParamsWithContext(ctx context.Context) *ReposUpdateRepoParams {
	var ()
	return &ReposUpdateRepoParams{

		Context: ctx,
	}
}

// NewReposUpdateRepoParamsWithHTTPClient creates a new ReposUpdateRepoParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewReposUpdateRepoParamsWithHTTPClient(client *http.Client) *ReposUpdateRepoParams {
	var ()
	return &ReposUpdateRepoParams{
		HTTPClient: client,
	}
}

/*ReposUpdateRepoParams contains all the parameters to send to the API endpoint
for the repos update repo operation typically these are written to a http.Request
*/
type ReposUpdateRepoParams struct {

	/*Project
	  A unique value identifying this project repo.

	*/
	Project string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the repos update repo params
func (o *ReposUpdateRepoParams) WithTimeout(timeout time.Duration) *ReposUpdateRepoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the repos update repo params
func (o *ReposUpdateRepoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the repos update repo params
func (o *ReposUpdateRepoParams) WithContext(ctx context.Context) *ReposUpdateRepoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the repos update repo params
func (o *ReposUpdateRepoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the repos update repo params
func (o *ReposUpdateRepoParams) WithHTTPClient(client *http.Client) *ReposUpdateRepoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the repos update repo params
func (o *ReposUpdateRepoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProject adds the project to the repos update repo params
func (o *ReposUpdateRepoParams) WithProject(project string) *ReposUpdateRepoParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the repos update repo params
func (o *ReposUpdateRepoParams) SetProject(project string) {
	o.Project = project
}

// WriteToRequest writes these params to a swagger request
func (o *ReposUpdateRepoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param project
	if err := r.SetPathParam("project", o.Project); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
