// Code generated by go-swagger; DO NOT EDIT.

package repos

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewReposDeleteParams creates a new ReposDeleteParams object
// with the default values initialized.
func NewReposDeleteParams() *ReposDeleteParams {
	var ()
	return &ReposDeleteParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewReposDeleteParamsWithTimeout creates a new ReposDeleteParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewReposDeleteParamsWithTimeout(timeout time.Duration) *ReposDeleteParams {
	var ()
	return &ReposDeleteParams{

		timeout: timeout,
	}
}

// NewReposDeleteParamsWithContext creates a new ReposDeleteParams object
// with the default values initialized, and the ability to set a context for a request
func NewReposDeleteParamsWithContext(ctx context.Context) *ReposDeleteParams {
	var ()
	return &ReposDeleteParams{

		Context: ctx,
	}
}

// NewReposDeleteParamsWithHTTPClient creates a new ReposDeleteParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewReposDeleteParamsWithHTTPClient(client *http.Client) *ReposDeleteParams {
	var ()
	return &ReposDeleteParams{
		HTTPClient: client,
	}
}

/*ReposDeleteParams contains all the parameters to send to the API endpoint
for the repos delete operation typically these are written to a http.Request
*/
type ReposDeleteParams struct {

	/*Project
	  A unique value identifying this project repo.

	*/
	Project string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the repos delete params
func (o *ReposDeleteParams) WithTimeout(timeout time.Duration) *ReposDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the repos delete params
func (o *ReposDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the repos delete params
func (o *ReposDeleteParams) WithContext(ctx context.Context) *ReposDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the repos delete params
func (o *ReposDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the repos delete params
func (o *ReposDeleteParams) WithHTTPClient(client *http.Client) *ReposDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the repos delete params
func (o *ReposDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProject adds the project to the repos delete params
func (o *ReposDeleteParams) WithProject(project string) *ReposDeleteParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the repos delete params
func (o *ReposDeleteParams) SetProject(project string) {
	o.Project = project
}

// WriteToRequest writes these params to a swagger request
func (o *ReposDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param project
	if err := r.SetPathParam("project", o.Project); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
