// Code generated by go-swagger; DO NOT EDIT.

package repos

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ReposListReader is a Reader for the ReposList structure.
type ReposListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ReposListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewReposListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewReposListOK creates a ReposListOK with default headers values
func NewReposListOK() *ReposListOK {
	return &ReposListOK{}
}

/*ReposListOK handles this case with default header values.

ReposListOK repos list o k
*/
type ReposListOK struct {
	Payload interface{}
}

func (o *ReposListOK) Error() string {
	return fmt.Sprintf("[GET /v3/customer/core/repos/][%d] reposListOK  %+v", 200, o.Payload)
}

func (o *ReposListOK) GetPayload() interface{} {
	return o.Payload
}

func (o *ReposListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
