// Code generated by go-swagger; DO NOT EDIT.

package pull_request_events

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PullRequestEventsReadReader is a Reader for the PullRequestEventsRead structure.
type PullRequestEventsReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PullRequestEventsReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPullRequestEventsReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPullRequestEventsReadOK creates a PullRequestEventsReadOK with default headers values
func NewPullRequestEventsReadOK() *PullRequestEventsReadOK {
	return &PullRequestEventsReadOK{}
}

/*PullRequestEventsReadOK handles this case with default header values.

PullRequestEventsReadOK pull request events read o k
*/
type PullRequestEventsReadOK struct {
	Payload interface{}
}

func (o *PullRequestEventsReadOK) Error() string {
	return fmt.Sprintf("[GET /v3/customer/core/pull_request_events/{id}/][%d] pullRequestEventsReadOK  %+v", 200, o.Payload)
}

func (o *PullRequestEventsReadOK) GetPayload() interface{} {
	return o.Payload
}

func (o *PullRequestEventsReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
