// Code generated by go-swagger; DO NOT EDIT.

package pull_request_events

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewPullRequestEventsListParams creates a new PullRequestEventsListParams object
// with the default values initialized.
func NewPullRequestEventsListParams() *PullRequestEventsListParams {
	var ()
	return &PullRequestEventsListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPullRequestEventsListParamsWithTimeout creates a new PullRequestEventsListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPullRequestEventsListParamsWithTimeout(timeout time.Duration) *PullRequestEventsListParams {
	var ()
	return &PullRequestEventsListParams{

		timeout: timeout,
	}
}

// NewPullRequestEventsListParamsWithContext creates a new PullRequestEventsListParams object
// with the default values initialized, and the ability to set a context for a request
func NewPullRequestEventsListParamsWithContext(ctx context.Context) *PullRequestEventsListParams {
	var ()
	return &PullRequestEventsListParams{

		Context: ctx,
	}
}

// NewPullRequestEventsListParamsWithHTTPClient creates a new PullRequestEventsListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPullRequestEventsListParamsWithHTTPClient(client *http.Client) *PullRequestEventsListParams {
	var ()
	return &PullRequestEventsListParams{
		HTTPClient: client,
	}
}

/*PullRequestEventsListParams contains all the parameters to send to the API endpoint
for the pull request events list operation typically these are written to a http.Request
*/
type PullRequestEventsListParams struct {

	/*ApexUserID
	  Match on apex_user_id (pr creator)

	*/
	ApexUserID *float64
	/*ApexUserIDIn
	  Match on apex_user_id (pr creator) in a comma separated list

	*/
	ApexUserIDIn *string
	/*Filters
	  Complex filter that handles filtering with groups of conditions connected with AND and OR conjunctions. The query can be arbitrarily grouped and nested.

	*/
	Filters *string
	/*ID*/
	ID *float64
	/*IDIn
	  Multiple values may be separated by commas.

	*/
	IDIn *float64
	/*Limit
	  Number of results to return per page.

	*/
	Limit *int64
	/*Offset
	  The initial index from which to return the results.

	*/
	Offset *int64
	/*Ordering
	  Valid ordering fields are: `id`, `user_alias_id`, `created_at`

	*/
	Ordering *string
	/*PullRequestID
	  ID of associated pull request

	*/
	PullRequestID *float64
	/*PullRequestIDIn
	  Match on pull_request_id in a comma separated list

	*/
	PullRequestIDIn *string
	/*Search
	  A search term.

	*/
	Search *string
	/*ToState*/
	ToState *string
	/*ToStateIn
	  Mulitple values may be separated by commas.

	*/
	ToStateIn *string
	/*UserAliasID*/
	UserAliasID *string
	/*UserAliasIDIn
	  Multiple values may be separated by commas.

	*/
	UserAliasIDIn *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the pull request events list params
func (o *PullRequestEventsListParams) WithTimeout(timeout time.Duration) *PullRequestEventsListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the pull request events list params
func (o *PullRequestEventsListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the pull request events list params
func (o *PullRequestEventsListParams) WithContext(ctx context.Context) *PullRequestEventsListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the pull request events list params
func (o *PullRequestEventsListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the pull request events list params
func (o *PullRequestEventsListParams) WithHTTPClient(client *http.Client) *PullRequestEventsListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the pull request events list params
func (o *PullRequestEventsListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithApexUserID adds the apexUserID to the pull request events list params
func (o *PullRequestEventsListParams) WithApexUserID(apexUserID *float64) *PullRequestEventsListParams {
	o.SetApexUserID(apexUserID)
	return o
}

// SetApexUserID adds the apexUserId to the pull request events list params
func (o *PullRequestEventsListParams) SetApexUserID(apexUserID *float64) {
	o.ApexUserID = apexUserID
}

// WithApexUserIDIn adds the apexUserIDIn to the pull request events list params
func (o *PullRequestEventsListParams) WithApexUserIDIn(apexUserIDIn *string) *PullRequestEventsListParams {
	o.SetApexUserIDIn(apexUserIDIn)
	return o
}

// SetApexUserIDIn adds the apexUserIdIn to the pull request events list params
func (o *PullRequestEventsListParams) SetApexUserIDIn(apexUserIDIn *string) {
	o.ApexUserIDIn = apexUserIDIn
}

// WithFilters adds the filters to the pull request events list params
func (o *PullRequestEventsListParams) WithFilters(filters *string) *PullRequestEventsListParams {
	o.SetFilters(filters)
	return o
}

// SetFilters adds the filters to the pull request events list params
func (o *PullRequestEventsListParams) SetFilters(filters *string) {
	o.Filters = filters
}

// WithID adds the id to the pull request events list params
func (o *PullRequestEventsListParams) WithID(id *float64) *PullRequestEventsListParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the pull request events list params
func (o *PullRequestEventsListParams) SetID(id *float64) {
	o.ID = id
}

// WithIDIn adds the iDIn to the pull request events list params
func (o *PullRequestEventsListParams) WithIDIn(iDIn *float64) *PullRequestEventsListParams {
	o.SetIDIn(iDIn)
	return o
}

// SetIDIn adds the idIn to the pull request events list params
func (o *PullRequestEventsListParams) SetIDIn(iDIn *float64) {
	o.IDIn = iDIn
}

// WithLimit adds the limit to the pull request events list params
func (o *PullRequestEventsListParams) WithLimit(limit *int64) *PullRequestEventsListParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the pull request events list params
func (o *PullRequestEventsListParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithOffset adds the offset to the pull request events list params
func (o *PullRequestEventsListParams) WithOffset(offset *int64) *PullRequestEventsListParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the pull request events list params
func (o *PullRequestEventsListParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WithOrdering adds the ordering to the pull request events list params
func (o *PullRequestEventsListParams) WithOrdering(ordering *string) *PullRequestEventsListParams {
	o.SetOrdering(ordering)
	return o
}

// SetOrdering adds the ordering to the pull request events list params
func (o *PullRequestEventsListParams) SetOrdering(ordering *string) {
	o.Ordering = ordering
}

// WithPullRequestID adds the pullRequestID to the pull request events list params
func (o *PullRequestEventsListParams) WithPullRequestID(pullRequestID *float64) *PullRequestEventsListParams {
	o.SetPullRequestID(pullRequestID)
	return o
}

// SetPullRequestID adds the pullRequestId to the pull request events list params
func (o *PullRequestEventsListParams) SetPullRequestID(pullRequestID *float64) {
	o.PullRequestID = pullRequestID
}

// WithPullRequestIDIn adds the pullRequestIDIn to the pull request events list params
func (o *PullRequestEventsListParams) WithPullRequestIDIn(pullRequestIDIn *string) *PullRequestEventsListParams {
	o.SetPullRequestIDIn(pullRequestIDIn)
	return o
}

// SetPullRequestIDIn adds the pullRequestIdIn to the pull request events list params
func (o *PullRequestEventsListParams) SetPullRequestIDIn(pullRequestIDIn *string) {
	o.PullRequestIDIn = pullRequestIDIn
}

// WithSearch adds the search to the pull request events list params
func (o *PullRequestEventsListParams) WithSearch(search *string) *PullRequestEventsListParams {
	o.SetSearch(search)
	return o
}

// SetSearch adds the search to the pull request events list params
func (o *PullRequestEventsListParams) SetSearch(search *string) {
	o.Search = search
}

// WithToState adds the toState to the pull request events list params
func (o *PullRequestEventsListParams) WithToState(toState *string) *PullRequestEventsListParams {
	o.SetToState(toState)
	return o
}

// SetToState adds the toState to the pull request events list params
func (o *PullRequestEventsListParams) SetToState(toState *string) {
	o.ToState = toState
}

// WithToStateIn adds the toStateIn to the pull request events list params
func (o *PullRequestEventsListParams) WithToStateIn(toStateIn *string) *PullRequestEventsListParams {
	o.SetToStateIn(toStateIn)
	return o
}

// SetToStateIn adds the toStateIn to the pull request events list params
func (o *PullRequestEventsListParams) SetToStateIn(toStateIn *string) {
	o.ToStateIn = toStateIn
}

// WithUserAliasID adds the userAliasID to the pull request events list params
func (o *PullRequestEventsListParams) WithUserAliasID(userAliasID *string) *PullRequestEventsListParams {
	o.SetUserAliasID(userAliasID)
	return o
}

// SetUserAliasID adds the userAliasId to the pull request events list params
func (o *PullRequestEventsListParams) SetUserAliasID(userAliasID *string) {
	o.UserAliasID = userAliasID
}

// WithUserAliasIDIn adds the userAliasIDIn to the pull request events list params
func (o *PullRequestEventsListParams) WithUserAliasIDIn(userAliasIDIn *string) *PullRequestEventsListParams {
	o.SetUserAliasIDIn(userAliasIDIn)
	return o
}

// SetUserAliasIDIn adds the userAliasIdIn to the pull request events list params
func (o *PullRequestEventsListParams) SetUserAliasIDIn(userAliasIDIn *string) {
	o.UserAliasIDIn = userAliasIDIn
}

// WriteToRequest writes these params to a swagger request
func (o *PullRequestEventsListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ApexUserID != nil {

		// query param apex_user_id
		var qrApexUserID float64
		if o.ApexUserID != nil {
			qrApexUserID = *o.ApexUserID
		}
		qApexUserID := swag.FormatFloat64(qrApexUserID)
		if qApexUserID != "" {
			if err := r.SetQueryParam("apex_user_id", qApexUserID); err != nil {
				return err
			}
		}

	}

	if o.ApexUserIDIn != nil {

		// query param apex_user_id__in
		var qrApexUserIDIn string
		if o.ApexUserIDIn != nil {
			qrApexUserIDIn = *o.ApexUserIDIn
		}
		qApexUserIDIn := qrApexUserIDIn
		if qApexUserIDIn != "" {
			if err := r.SetQueryParam("apex_user_id__in", qApexUserIDIn); err != nil {
				return err
			}
		}

	}

	if o.Filters != nil {

		// query param filters
		var qrFilters string
		if o.Filters != nil {
			qrFilters = *o.Filters
		}
		qFilters := qrFilters
		if qFilters != "" {
			if err := r.SetQueryParam("filters", qFilters); err != nil {
				return err
			}
		}

	}

	if o.ID != nil {

		// query param id
		var qrID float64
		if o.ID != nil {
			qrID = *o.ID
		}
		qID := swag.FormatFloat64(qrID)
		if qID != "" {
			if err := r.SetQueryParam("id", qID); err != nil {
				return err
			}
		}

	}

	if o.IDIn != nil {

		// query param id__in
		var qrIDIn float64
		if o.IDIn != nil {
			qrIDIn = *o.IDIn
		}
		qIDIn := swag.FormatFloat64(qrIDIn)
		if qIDIn != "" {
			if err := r.SetQueryParam("id__in", qIDIn); err != nil {
				return err
			}
		}

	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	if o.Ordering != nil {

		// query param ordering
		var qrOrdering string
		if o.Ordering != nil {
			qrOrdering = *o.Ordering
		}
		qOrdering := qrOrdering
		if qOrdering != "" {
			if err := r.SetQueryParam("ordering", qOrdering); err != nil {
				return err
			}
		}

	}

	if o.PullRequestID != nil {

		// query param pull_request_id
		var qrPullRequestID float64
		if o.PullRequestID != nil {
			qrPullRequestID = *o.PullRequestID
		}
		qPullRequestID := swag.FormatFloat64(qrPullRequestID)
		if qPullRequestID != "" {
			if err := r.SetQueryParam("pull_request_id", qPullRequestID); err != nil {
				return err
			}
		}

	}

	if o.PullRequestIDIn != nil {

		// query param pull_request_id__in
		var qrPullRequestIDIn string
		if o.PullRequestIDIn != nil {
			qrPullRequestIDIn = *o.PullRequestIDIn
		}
		qPullRequestIDIn := qrPullRequestIDIn
		if qPullRequestIDIn != "" {
			if err := r.SetQueryParam("pull_request_id__in", qPullRequestIDIn); err != nil {
				return err
			}
		}

	}

	if o.Search != nil {

		// query param search
		var qrSearch string
		if o.Search != nil {
			qrSearch = *o.Search
		}
		qSearch := qrSearch
		if qSearch != "" {
			if err := r.SetQueryParam("search", qSearch); err != nil {
				return err
			}
		}

	}

	if o.ToState != nil {

		// query param to_state
		var qrToState string
		if o.ToState != nil {
			qrToState = *o.ToState
		}
		qToState := qrToState
		if qToState != "" {
			if err := r.SetQueryParam("to_state", qToState); err != nil {
				return err
			}
		}

	}

	if o.ToStateIn != nil {

		// query param to_state__in
		var qrToStateIn string
		if o.ToStateIn != nil {
			qrToStateIn = *o.ToStateIn
		}
		qToStateIn := qrToStateIn
		if qToStateIn != "" {
			if err := r.SetQueryParam("to_state__in", qToStateIn); err != nil {
				return err
			}
		}

	}

	if o.UserAliasID != nil {

		// query param user_alias_id
		var qrUserAliasID string
		if o.UserAliasID != nil {
			qrUserAliasID = *o.UserAliasID
		}
		qUserAliasID := qrUserAliasID
		if qUserAliasID != "" {
			if err := r.SetQueryParam("user_alias_id", qUserAliasID); err != nil {
				return err
			}
		}

	}

	if o.UserAliasIDIn != nil {

		// query param user_alias_id__in
		var qrUserAliasIDIn string
		if o.UserAliasIDIn != nil {
			qrUserAliasIDIn = *o.UserAliasIDIn
		}
		qUserAliasIDIn := qrUserAliasIDIn
		if qUserAliasIDIn != "" {
			if err := r.SetQueryParam("user_alias_id__in", qUserAliasIDIn); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
