// Code generated by go-swagger; DO NOT EDIT.

package org_membership

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewOrgMembershipReadParams creates a new OrgMembershipReadParams object
// with the default values initialized.
func NewOrgMembershipReadParams() *OrgMembershipReadParams {
	var ()
	return &OrgMembershipReadParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewOrgMembershipReadParamsWithTimeout creates a new OrgMembershipReadParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewOrgMembershipReadParamsWithTimeout(timeout time.Duration) *OrgMembershipReadParams {
	var ()
	return &OrgMembershipReadParams{

		timeout: timeout,
	}
}

// NewOrgMembershipReadParamsWithContext creates a new OrgMembershipReadParams object
// with the default values initialized, and the ability to set a context for a request
func NewOrgMembershipReadParamsWithContext(ctx context.Context) *OrgMembershipReadParams {
	var ()
	return &OrgMembershipReadParams{

		Context: ctx,
	}
}

// NewOrgMembershipReadParamsWithHTTPClient creates a new OrgMembershipReadParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewOrgMembershipReadParamsWithHTTPClient(client *http.Client) *OrgMembershipReadParams {
	var ()
	return &OrgMembershipReadParams{
		HTTPClient: client,
	}
}

/*OrgMembershipReadParams contains all the parameters to send to the API endpoint
for the org membership read operation typically these are written to a http.Request
*/
type OrgMembershipReadParams struct {

	/*ID
	  A unique integer value identifying this org membership.

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the org membership read params
func (o *OrgMembershipReadParams) WithTimeout(timeout time.Duration) *OrgMembershipReadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the org membership read params
func (o *OrgMembershipReadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the org membership read params
func (o *OrgMembershipReadParams) WithContext(ctx context.Context) *OrgMembershipReadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the org membership read params
func (o *OrgMembershipReadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the org membership read params
func (o *OrgMembershipReadParams) WithHTTPClient(client *http.Client) *OrgMembershipReadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the org membership read params
func (o *OrgMembershipReadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the org membership read params
func (o *OrgMembershipReadParams) WithID(id int64) *OrgMembershipReadParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the org membership read params
func (o *OrgMembershipReadParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *OrgMembershipReadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
