// Code generated by go-swagger; DO NOT EDIT.

package org_membership

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// OrgMembershipReadReader is a Reader for the OrgMembershipRead structure.
type OrgMembershipReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OrgMembershipReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewOrgMembershipReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewOrgMembershipReadOK creates a OrgMembershipReadOK with default headers values
func NewOrgMembershipReadOK() *OrgMembershipReadOK {
	return &OrgMembershipReadOK{}
}

/*OrgMembershipReadOK handles this case with default header values.

OrgMembershipReadOK org membership read o k
*/
type OrgMembershipReadOK struct {
	Payload interface{}
}

func (o *OrgMembershipReadOK) Error() string {
	return fmt.Sprintf("[GET /v3/customer/core/org_membership/{id}/][%d] orgMembershipReadOK  %+v", 200, o.Payload)
}

func (o *OrgMembershipReadOK) GetPayload() interface{} {
	return o.Payload
}

func (o *OrgMembershipReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
