// Code generated by go-swagger; DO NOT EDIT.

package org_invites

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewOrgInvitesBulkCreateParams creates a new OrgInvitesBulkCreateParams object
// with the default values initialized.
func NewOrgInvitesBulkCreateParams() *OrgInvitesBulkCreateParams {
	var ()
	return &OrgInvitesBulkCreateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewOrgInvitesBulkCreateParamsWithTimeout creates a new OrgInvitesBulkCreateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewOrgInvitesBulkCreateParamsWithTimeout(timeout time.Duration) *OrgInvitesBulkCreateParams {
	var ()
	return &OrgInvitesBulkCreateParams{

		timeout: timeout,
	}
}

// NewOrgInvitesBulkCreateParamsWithContext creates a new OrgInvitesBulkCreateParams object
// with the default values initialized, and the ability to set a context for a request
func NewOrgInvitesBulkCreateParamsWithContext(ctx context.Context) *OrgInvitesBulkCreateParams {
	var ()
	return &OrgInvitesBulkCreateParams{

		Context: ctx,
	}
}

// NewOrgInvitesBulkCreateParamsWithHTTPClient creates a new OrgInvitesBulkCreateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewOrgInvitesBulkCreateParamsWithHTTPClient(client *http.Client) *OrgInvitesBulkCreateParams {
	var ()
	return &OrgInvitesBulkCreateParams{
		HTTPClient: client,
	}
}

/*OrgInvitesBulkCreateParams contains all the parameters to send to the API endpoint
for the org invites bulk create operation typically these are written to a http.Request
*/
type OrgInvitesBulkCreateParams struct {

	/*Data*/
	Data OrgInvitesBulkCreateBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the org invites bulk create params
func (o *OrgInvitesBulkCreateParams) WithTimeout(timeout time.Duration) *OrgInvitesBulkCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the org invites bulk create params
func (o *OrgInvitesBulkCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the org invites bulk create params
func (o *OrgInvitesBulkCreateParams) WithContext(ctx context.Context) *OrgInvitesBulkCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the org invites bulk create params
func (o *OrgInvitesBulkCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the org invites bulk create params
func (o *OrgInvitesBulkCreateParams) WithHTTPClient(client *http.Client) *OrgInvitesBulkCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the org invites bulk create params
func (o *OrgInvitesBulkCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the org invites bulk create params
func (o *OrgInvitesBulkCreateParams) WithData(data OrgInvitesBulkCreateBody) *OrgInvitesBulkCreateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the org invites bulk create params
func (o *OrgInvitesBulkCreateParams) SetData(data OrgInvitesBulkCreateBody) {
	o.Data = data
}

// WriteToRequest writes these params to a swagger request
func (o *OrgInvitesBulkCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Data); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
